# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:
  - build
  - release

build:  
  stage: build
  image: ubuntu:latest
  before_script:
    - echo $CI_JOB_ID
    - echo BUILD_JOB_ID=$CI_JOB_ID >> build.env
    - cat VERSION >> build.env
  script:
    - ./mkpkg

  # This stage is only executed for new tags
  only:
    - tags

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - dist/*.deb
      - dist/*.rpm
    reports:
      dotenv: build.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo 'running release_job'
    - echo 'Previous Job ID:'
    - echo $BUILD_JOB_ID
    - echo 'VERSION:'
    - echo $VERSION
    - echo 'RELEASE:'
    - echo $RELEASE
  needs:
    - job: build
      artifacts: true
  release:
    name: 'MirrorImages Version $VERSION release $RELEASE'
    description: './release.md'
    tag_name: 'v${VERSION}r${RELEASE}'
    assets:
      links:
        - name: 'TantraTutorial_${VERSION}-${RELEASE}.deb - Tantra Tutorial Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/TantraTutorial_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'TantraTutorial_${VERSION}-${RELEASE}.rpm - Tantra Tutorial RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/TantraTutorial_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'PhotographersLandscape_${VERSION}-${RELEASE}.deb - Landscape mode Photographers images Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/PhotographersLandscape_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'PhotographersPortrait_${VERSION}-${RELEASE}.deb - Portrait mode Photographers images Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/PhotographersPortrait_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'PhotographersLandscape_${VERSION}-${RELEASE}.rpm - Landscape mode Photographers images RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/PhotographersLandscape_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'PhotographersPortrait_${VERSION}-${RELEASE}.rpm - Portrait mode Photographers images RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/PhotographersPortrait_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'ModelsLandscape_${VERSION}-${RELEASE}.deb - Landscape mode Models images Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ModelsLandscape_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'ModelsPortrait_${VERSION}-${RELEASE}.deb - Portrait mode Models images Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ModelsPortrait_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'ModelsLandscape_${VERSION}-${RELEASE}.rpm - Landscape mode Models images RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ModelsLandscape_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'ModelsPortrait_${VERSION}-${RELEASE}.rpm - Portrait mode Models images RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ModelsPortrait_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'JavLandscape_${VERSION}-${RELEASE}.deb - Landscape mode JAV images Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/JavLandscape_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'JavPortrait_${VERSION}-${RELEASE}.deb - Portrait mode JAV images Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/JavPortrait_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'JavLandscape_${VERSION}-${RELEASE}.rpm - Landscape mode JAV images RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/JavLandscape_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'JavPortrait_${VERSION}-${RELEASE}.rpm - Portrait mode JAV images RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/JavPortrait_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'CountriesLandscape_${VERSION}-${RELEASE}.deb - Landscape mode Countries models landscape images Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/CountriesLandscape_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'CountriesPortrait_${VERSION}-${RELEASE}.deb - Portrait mode Countries models images Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/CountriesPortrait_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'CountriesLandscape_${VERSION}-${RELEASE}.rpm - Landscape mode Countries models landscape images RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/CountriesLandscape_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'CountriesPortrait_${VERSION}-${RELEASE}.rpm - Portrait mode Countries models images RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/CountriesPortrait_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'ArtistsLandscape_${VERSION}-${RELEASE}.deb - Landscape mode Artists landscape images Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ArtistsLandscape_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'ArtistsPortrait_${VERSION}-${RELEASE}.deb - Portrait mode Artists images Debian format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ArtistsPortrait_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'ArtistsLandscape_${VERSION}-${RELEASE}.rpm - Landscape mode Artists landscape images RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ArtistsLandscape_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'ArtistsPortrait_${VERSION}-${RELEASE}.rpm - Portrait mode Artists images RPM format installation package (Rated R)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ArtistsPortrait_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'ImagesLandscape_${VERSION}-${RELEASE}.deb - Landscape mode images Debian format installation package (Rated G)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ImagesLandscape_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'ImagesPortrait_${VERSION}-${RELEASE}.deb - Portrait mode images Debian format installation package (Rated G)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ImagesPortrait_${VERSION}-${RELEASE}.deb'
          link_type: 'package'
        - name: 'ImagesLandscape_${VERSION}-${RELEASE}.rpm - Landscape mode images RPM format installation package (Rated G)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ImagesLandscape_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
        - name: 'ImagesPortrait_${VERSION}-${RELEASE}.rpm - Portrait mode images RPM format installation package (Rated G)'
          url: 'https://gitlab.com/doctorfree/MirrorImages/-/jobs/${BUILD_JOB_ID}/artifacts/file/dist/ImagesPortrait_${VERSION}-${RELEASE}.rpm'
          link_type: 'package'
  only:
    - tags
