#!/bin/bash
PKG="images-portrait"
SRC_NAME="MirrorImages"
PKG_NAME="ImagesPortrait"
TOP="usr"
DESTDIR="${TOP}/local"
MM="${DESTDIR}/MirrorCommand"
SRC=${HOME}/src
SUDO=sudo
GCI=

dpkg=`type -p dpkg-deb`
[ "${dpkg}" ] || {
    echo "Debian packaging tools do not appear to be installed on this system"
    echo "Are you on the appropriate Linux system with packaging requirements ?"
    echo "Exiting"
    exit 1
}

[ -f "${SRC}/${SRC_NAME}/VERSION" ] || {
  [ -f "/builds/doctorfree/${SRC_NAME}/VERSION" ] || {
    echo "$SRC/$SRC_NAME/VERSION does not exist. Exiting."
    exit 1
  }
  SRC="/builds/doctorfree"
  SUDO=
  GCI=1
}

. "${SRC}/${SRC_NAME}/VERSION"
PKG_VER=${VERSION}
PKG_REL=${RELEASE}

# umask 0022

# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d "${SRC}/${SRC_NAME}" ] || {
    echo "$SRC/$SRC_NAME does not exist or is not a directory. Exiting."
    exit 1
}

cd "${SRC}/${SRC_NAME}"
${SUDO} rm -rf dist
mkdir dist

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}

cp -a pkg/images-portrait ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 375000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Portrait Format Images
 Images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="photographers-portrait"
PKG_NAME="PhotographersPortrait"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/photographers-portrait ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 500000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Portrait Format Photographer Images
 Photographer Images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="jav-portrait"
PKG_NAME="JavPortrait"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/jav-portrait ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 500000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Portrait Format JAV Images
 JAV Images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="jav-landscape"
PKG_NAME="JavLandscape"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/jav-landscape ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 500000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Landscape Format JAV Images
 JAV Images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="artists-portrait"
PKG_NAME="ArtistsPortrait"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/artists-portrait ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 5400000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Portrait Format Artists Images
 Artists Images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="countries-portrait"
PKG_NAME="CountriesPortrait"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/countries-portrait ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 5400000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Portrait Format Countries model Images
 Countries model images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="models-portrait"
PKG_NAME="ModelsPortrait"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/models-portrait ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 4700000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Portrait Format Models Images
 Models Images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="images-landscape"
PKG_NAME="ImagesLandscape"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/images-landscape ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 500000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Landscape Format Images
 Images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="photographers-landscape"
PKG_NAME="PhotographersLandscape"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/photographers-landscape ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 500000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Landscape Format Photographer Images
 Photographer Images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="artists-landscape"
PKG_NAME="ArtistsLandscape"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/artists-landscape ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 5400000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Landscape Format Artists Images
 Artists Images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="countries-landscape"
PKG_NAME="CountriesLandscape"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/countries-landscape ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 5400000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Landscape Format Countries model Images
 Countries model images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="models-landscape"
PKG_NAME="ModelsLandscape"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/models-landscape ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 4700000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Landscape Format Models Images
 Models Images for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

cd "${SRC}/${SRC_NAME}"

PKG="tantra-tutorial"
PKG_NAME="TantraTutorial"
# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
cp -a pkg/tantra-tutorial ${OUT_DIR}/DEBIAN
chmod 755 ${OUT_DIR} ${OUT_DIR}/DEBIAN ${OUT_DIR}/DEBIAN/*

echo "Package: ${PKG}
Version: ${PKG_VER}-${PKG_REL}
Section: misc
Priority: optional
Architecture: all
Depends: mirrorcommand (>= 3.0.0)
Installled-Size: 4700000
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/MirrorImages
Description: MagicMirror Tantra Tutorial
 Tantra Tutorial videos for a MagicMirror using the MirrorCommand configs" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${MM}" "${DESTDIR}/share" \
           "${DESTDIR}/share/doc" "${DESTDIR}/share/doc/${PKG}"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

[ -d ${OUT_DIR}/${MM} ] || ${SUDO} mkdir ${OUT_DIR}/${MM}
[ -d ${OUT_DIR}/${MM}/movies ] || ${SUDO} mkdir ${OUT_DIR}/${MM}/movies
[ -f movies/tantralist.txt ] && ${SUDO} cp movies/tantralist.txt ${OUT_DIR}/${MM}/movies

${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb

# RPM distribution build
cd "${SRC}/${SRC_NAME}"
echo "Building RPM packages in ${SRC}/${SRC_NAME}"
[ -d ${OUT_DIR}/rpm ] || mkdir ${OUT_DIR}/rpm

type -p rpmbuild > /dev/null || {
  ${SUDO} apt-get update
  export DEBIAN_FRONTEND=noninteractive
  ${SUDO} ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
  ${SUDO} apt-get install rpm -y
  ${SUDO} dpkg-reconfigure --frontend noninteractive tzdata
}

for pkg in ArtistsLandscape ArtistsPortrait CountriesLandscape \
           CountriesPortrait ImagesLandscape ImagesPortrait \
           JavLandscape JavPortrait ModelsLandscape ModelsPortrait \
           PhotographersLandscape PhotographersPortrait TantraTutorial
do
  rm -f ${OUT_DIR}/rpm/MirrorImages.spec
  [ -f pkg/rpm/${pkg}/MirrorImages.spec ] && {
    cp pkg/rpm/${pkg}/MirrorImages.spec ${OUT_DIR}/rpm/MirrorImages.spec
    rpmbuild -ba --build-in-place \
      --define "_topdir ${OUT_DIR}" \
      --define "_sourcedir ${OUT_DIR}" \
      --define "_version ${PKG_VER}" \
      --define "_release ${PKG_REL}" \
      --buildroot ${SRC}/${SRC_NAME}/${OUT_DIR}/BUILDROOT \
      ${OUT_DIR}/rpm/MirrorImages.spec
  }
done

# Rename RPMs if necessary
for rpmfile in ${OUT_DIR}/RPMS/*/*.rpm
do
  [ "${rpmfile}" == "${OUT_DIR}/RPMS/*/*.rpm" ] && continue
  rpmbas=`basename ${rpmfile}`
  rpmdir=`dirname ${rpmfile}`
  newnam=`echo ${rpmbas} | sed -e "s/${PKG_NAME}-${PKG_VER}-${PKG_REL}/${PKG_NAME}_${PKG_VER}-${PKG_REL}/" -e "s/noarch.rpm/rpm/"`
  [ "${rpmbas}" == "${newnam}" ] && continue
  mv ${rpmdir}/${rpmbas} ${rpmdir}/${newnam}
done

${SUDO} cp ${OUT_DIR}/RPMS/*/*.rpm dist

[ "${GCI}" ] || {
    [ -d releases ] || mkdir releases
    [ -d releases/${PKG_VER} ] || mkdir releases/${PKG_VER}
    ${SUDO} cp ${OUT_DIR}/RPMS/*/*.rpm releases/${PKG_VER}
    ${SUDO} cp dist/*.deb releases/${PKG_VER}
}

