#!/bin/bash

for pkg in artists-portrait \
           jav-portrait \
           models-portrait \
           photographers-portrait \
           tantra-tutorial \
           images-portrait \
           jav-landscape \
           models-landscape \
           photographers-landscape \
           artists-landscape \
do
    dpkg -s ${pkg} > /dev/null 2>&1
    retVal=$?
    [ ${retVal} -eq 0 ] && {
        echo "Removing ${pkg}"
        sudo apt remove ${pkg} -y
    }
done
