#!/bin/bash
# prerm script for tantra-tutorial
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    remove|upgrade|deconfigure)
        MM="/usr/local/MirrorCommand"
        [ -d ${MM}/movies ] && {
          REMOVE=1
          while true
          do
            read -p "Remove previously downloaded videos? ('Y'/'N'): " yn
            case $yn in
                [Yy]*)
                    break
                    ;;
                [Nn]*)
                    REMOVE=
                    break
                    ;;
                * )
                    echo "Please answer yes or no."
                    ;;
            esac
          done
          [ "${REMOVE}" ] && {
            if [ -f ${MM}/movies/tantralist.txt ]
            then
              while read img
              do
                rm -f ${MM}/movies/${img}
              done < ${MM}/movies/tantralist.txt
              rm -f ${MM}/movies/tantralist.txt
              for subdir in Tantra
              do
                for folder in ${MM}/movies/${subdir}/*
                do
                  [ "${folder}" == "${MM}/movies/${subdir}/*" ] || {
                    [ -d "${folder}" ] && rmdir --ignore-fail-on-non-empty "${folder}"
                  }
                done
                [ -d ${MM}/movies/${subdir} ] && {
                    rmdir --ignore-fail-on-non-empty ${MM}/movies/${subdir}
                }
              done
            else
              for subdir in Tantra
              do
                rm -rf ${MM}/movies/${subdir}
              done
            fi
            # Remove any symbolic links in the movies directory
            for folder in ${MM}/movies/*
            do
              [ "${folder}" == "${MM}/movies/*" ] && continue
              [ -L "${folder}" ] && {
                  rm -f "${folder}"
              }
            done
          }
        }
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
